CREATE TABLE recipe_member
(
ID VARCHAR2(100) PRIMARY KEY ,
NAME VARCHAR2(100) NOT NULL ,
PASSWORD VARCHAR2(100) NOT NULL ,
ADDRESS VARCHAR2(100) NOT NULL ,
SIGN_IN_DATE DATE DEFAULT SYSDATE ,
BIRTHDAY DATE NOT NULL ,
EMAIL VARCHAR2(100) NOT NULL ,
TEL VARCHAR2(100) NOT NULL
);

select * from recipe_member;