CREATE TABLE category
(
CATEGORY_NUM NUMBER PRIMARY KEY ,
CATEGORY_NAME VARCHAR2(100) NOT NULL
);

CREATE TABLE recipe
(
RECIPE_NUM NUMBER PRIMARY KEY,
ID VARCHAR2(100) NOT NULL ,
TITLE VARCHAR2(100) NOT NULL ,
CONTENT CLOB NOT NULL ,
HITS NUMBER default 0,
LIKES NUMBER default 0,
REG_DATE DATE default sysdate ,
CATEGORY_NUM NUMBER NOT NULL,
image VARCHAR2(100) NOT NULL,
CONSTRAINT recipe_fk1 FOREIGN KEY(ID) REFERENCES recipe_member(id),
CONSTRAINT recipe_fk2 FOREIGN KEY(CATEGORY_NUM) REFERENCES category(category_num)
);

-- 주석달린것 생성하지 말 것
--ALTER TABLE RECIPE
-- ADD (CONSTRAINT recipe_fk1 FOREIGN KEY (ID) REFERENCES recipe_member(id));

--ALTER TABLE RECIPE
-- ADD (CONSTRAINT recipe_fk2 FOREIGN KEY (CATEGORY_NUM) REFERENCES category(category_num));

CREATE SEQUENCE recipe_seq NOCACHE;

-- 아래부분 생성하지 않음.  구현 후 생각해 볼 예정
CREATE TABLE image
(
IMAGE_NUM NUMBER NOT NULL ,
IMAGE_NAME VARCHAR2(100) NULL ,
CATEGORY_NUM NUMBER NOT NULL ,
RECIPE_NUM NUMBER NOT NULL ,
CONSTRAINT recipe_fk3 FOREIGN KEY(RECIPE_NUM) REFERENCES RECIPE(RECIPE_NUM)
);

select * from IMAGE; 
ALTER TABLE IMAGE
ADD (CONSTRAINT R_10 FOREIGN KEY (RECIPE_NUM) REFERENCES RECIPE(RECIPE_NUM));

insert into IMAGE (image_num, image_name, category_num, recipe_num)
values('1','erd-피지컬 진짜 최종.png','1','1');